### ISSUE TITLE
KeyError: 'authorization'

### ISSUE THREAD

**Issue by Lyfhael** [1220moritz/reverse-twitter-scraper#3]
Hi,

I launch the script below, and I get the error messages below:

Script:
```
from ReverseTwitterScraper import TwitterScraper

chromedriver_path = "C:/Users/hidden_username/Documents/latest_chromedriver/chromedriver.exe"
cookies = {'Cookie': 'external_referer="xxx==|1"; dnt=1; kdt=xxx; remember_checked_on=1; des_opt_in=Y; eu_cn=1; tweetdeck_version=beta; d_prefs=xxx; guest_id_ads=v1%xxx; guest_id_marketing=v1%xxx; _ga=xxx; night_mode=2; ads_prefs="xxx="; auth_multi="xxx|xxx; auth_token=xxx; personalization_id="xxx"; guest_id=v1%xxx; ct0=xxx; twid=u%xxx; lang=fr; at_check=true; mbox=PC#xxx; external_referer=xxx; _twitter_sess=xxx',
           'X-Csrf-Token': 'fb0fxxxb4379d3956efb68dc8'} #with account cookie
proxy_list = []


twitter_handle = ["elonmusk"]  # single account
# twitter_handles = ["elonmusk", "POTUS", "latestinspace"]  # multiple accounts
scraper = TwitterScraper(twitter_handle, chromedriver_path, cookies, proxy_list)
tweets = scraper.getTweetsText()

print(tweets)
```

Error message:
```

DevTools listening on ws://127.0.0.1:52600/devtools/browser/b5fxxxx-ee21-xxxx-91a4-d01xxx2fb229
[0706/093758.318:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093759.745:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for abs.twimg.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093801.411:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for accounts.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093802.137:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for api.twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found



DevTools listening on ws://127.0.0.1:52653/devtools/browser/d0bxxxx-514b-xxxx-84f7-f9exxxccb9d3
[0706/093807.994:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093809.383:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for abs.twimg.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093810.873:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for accounts.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093811.969:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for api.twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found



DevTools listening on ws://127.0.0.1:52709/devtools/browser/484xxxx-b152-xxxx-9af3-d80xxx37083c
[0706/093817.714:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093819.079:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for abs.twimg.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093820.605:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for accounts.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093821.477:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for api.twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found



DevTools listening on ws://127.0.0.1:52759/devtools/browser/6e4xxxx-1bf6-xxxx-aa28-2dexxxe105b0
[0706/093827.261:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093828.605:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for abs.twimg.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093830.255:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for accounts.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093830.946:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for api.twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found



DevTools listening on ws://127.0.0.1:52810/devtools/browser/f31xxxx-8ffd-xxxx-9cfa-d59xxxa69997
[0706/093836.768:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093838.149:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for abs.twimg.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093839.697:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for accounts.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093840.381:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for api.twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093842.489:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for appleid.cdn-apple.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found



DevTools listening on ws://127.0.0.1:52861/devtools/browser/b42xxxx-fa45-xxxx-b08f-95bxxx224181
[0706/093846.171:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093847.540:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for abs.twimg.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093849.535:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for accounts.google.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093850.197:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for api.twitter.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


[0706/093852.426:ERROR:cert_verify_proc_builtin.cc(702)] CertVerifyProcBuiltin for appleid.cdn-apple.com failed:
----- Certificate i=1 (CN=Selenium Wire CA) -----
ERROR: No matching issuer found


Traceback (most recent call last):
  File "C:\Users\hidden_username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ReverseTwitterScraper\Scraper.py", line 96, in __init__
    resp =  httpx.get(url=self.__reqUrl, headers=self.__headers, cookies=self.__cookies)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hidden_username\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_api.py", line 189, in get
    return request(
           ^^^^^^^^
  File "C:\Users\hidden_username\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
           ^^^^^^^^^^^^^^^
  File "C:\Users\hidden_username\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 808, in request
    request = self.build_request(
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hidden_username\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 348, in build_request
    url = self._merge_url(url)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hidden_username\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 378, in _merge_url
    merge_url = URL(url)
                ^^^^^^^^
  File "C:\Users\hidden_username\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_urls.py", line 89, in __init__
    raise TypeError(
TypeError: Invalid type for url.  Expected str or httpx.URL, got <class 'NoneType'>: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hidden_username\Documents\Programs\fetchtwitter.py", line 11, in <module>
    scraper = TwitterScraper(twitter_handle, chromedriver_path, cookies, proxy_list)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hidden_username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ReverseTwitterScraper\Scraper.py", line 105, in __init__
    self.getTwitterGuestData(cookies=self.__accCookies)
  File "C:\Users\hidden_username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ReverseTwitterScraper\Scraper.py", line 154, in getTwitterGuestData
    'authorization': headersDict['authorization'],
                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'authorization'
```

Replaced ids with 'xxx' characters.
I use chrome driver 114.0.5735.90 https://chromedriver.storage.googleapis.com/index.html?path=114.0.5735.90/

**Comment by 1220moritz** [comment]
This error usually comes up if the Selenium browser can't get any Authentication cookies. 
This makes sense because Twitter requires login now to view/scrape tweets. Even if you want to use account cookies with my scraper, it tries to get the auth cookies before and just sends the "getTweets" requests with account cookies. 
I think it's currently broken and I'm trying to fix asap.

**Comment by 1220moritz** [comment]
0.8 mandates the use of account cookies for viewing tweets. "Fixes" the problem
